= Ubuntu更新手順書

== 1. 事前準備

=== 1.1 対象のマシンのデータのバックアップ

必要に応じて写真、音楽、動画等のファイルやソースコードのバックアップを保存します。

チェックリスト

* [ ] 写真や画像
* [ ] 動画
* [ ] 音楽
* [ ] コード
* [ ] 鍵 (パスワード付き圧縮かUSBに保存)


=== 1.2 FireFoxの設定情報をバックアップ

下記のコマンドを実行しFireFoxの設定情報のバックアップを行います。 +

....
$ cd
$ tar zcvf firefox.tar.gz .mozilla
....

作成した `firefox.tar.gz` を別のストレージに保存します。


=== 1.3 Ubuntuの最新版のインストールメディアの作成

※ この節の内容はWindowsマシンで実行します。

Ubuntuの最新版のisoイメージを `https://www.ubuntu.com/download/desktop` からダウンロードします。 +
USBをインストールメディアとして使用できるようにするRufusを `https://rufus.ie` からダウンロードします。

上記２つのデータのダウンロード完了後、使用するUSBをWindows機に指した状態でRufusを起動してUbuntuのインストールメディアを作成します。 +
Rufusを起動後、選択ボタンをクリックしてダウンロードしたisoファイルを選択します。 +
その後、スタートを押してisoファイルをUSBに書き込みます。  


== 2. Ubuntuのインストール

※ この項の内容は `Ubuntu 19.04` をベースに書いています。適宜読み替えてください。

Ubuntuをインストールするマシンに1.3で作成したUSBを差してからマシンを起動します。 +
電源ボタンを押した後、 `F9` キーを連打してUSBのブートを選択します。 +

インストール手順に従いUbuntuをインストールします。 +
HDDは削除して綺麗な状態でインストールします。 +


== 3. インストール後

=== 3.1 WiFi設定

ログイン後、右上のメニューからWiFi設定を選択してWiFiに接続します。 +
`非表示のネットワークに接続` を選択し、ネットワーク名とパスワードを入力して接続します。 +

=== 3.2 インストール済みのパッケージのアップデート

ターミナルを開き、下記のコマンドを実行してアップデートを行います。 +

....
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get dist-upgrade
....

=== 3.3 よく使うパッケージのインストール

`vim` や `git` 等よく使用するパッケージのインストールを行います。 +

....
$ sudo apt-get install vim git
....

gitのコミット時に使用するユーザ名とパスワードの設定を行います。 +

....
$ git config --global user.email "k.igari1013@gmail.com"
$ git config --global user.name "iga_c"
....

=== 3.4 データを復元する

1.1でバックアップを保存したデータを元に戻します。 +

=== 3.5 FireFoxの設定ファイルを復元する

ホームディレクトリに1.2で作成した `firefox.tar.gz` を保存します。 +
その後、下記のコマンドを実行し解凍して設定ファイルを復元します。 +

....
$ tar zxvf firefox.tar.gz
$ ls -alh ~/
....

`ls` コマンドの結果に `.mozilla` ディレクトリが存在することを確認します。 +
